environment:
  matrix:
  - nodejs_version: "5.0"
  - nodejs_version: "0.10"

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

build: off
